version: "1.0"

services:
    server:
        image: 'nginx:stable-alpine'
        ports:
            - '8001:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/html
        depends_on:
            - php
            - mysql
    php:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes:
            - .:/var/www/html:delegated
    mysql:
        image: mysql:5.7
        env_file:
            - ./env/mysql.env
        ports:
            - '3306:3306'
        volumes:
            - ./mysql-data:/var/lib/mysql
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - '8180:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        depends_on:
            - mysql
    composer:
        build:
            context: .
            dockerfile: dockerfiles/composer.dockerfile
        volumes:
            - .:/var/www/html
    artisan:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes:
            - .:/var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
